### ISSUE TITLE
Tests Not Working in Ziffers2

### ISSUE THREAD

**Issue by Enkerli** [amiika/ziffers#42]
In Sonic Pi 3.3.1 using Ziffers2 branch from this morning, stopping at the first test:

https://github.com/amiika/ziffers/blob/53bad2da3f2ae0898d98ac6c0f5a6706d29cb118/play_tests.rb#L192

Getting the following error:
```
Runtime Error: [buffer 3, line 194] - NoMethodError
Thread death!
 undefined method `value' for nil:NilClass
~/ziffers/parser/zgrammar.rb:40:in `parse_ziffers'
~/ziffers/ziffers.rb:230:in `zparse'
~/ziffers/ziffers.rb:562:in `normalize_melody'
~/ziffers/ziffers.rb:435:in `zplay'
workspace_three:50:in `testinverseoffset'
workspace_three:194:in `block (2 levels) in __spider_eval'
/Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/lib/sonicpi/runtime.rb:830:in `eval'
/Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/lib/sonicpi/runtime.rb:830:in `block (2 levels) in __spider_eval'
/Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/lib/sonicpi/runtime.rb:1093:in `block (2 levels) in __in_thread'
```

**Comment by amiika** [comment]
Fixed in new release
